### ISSUE TITLE
请问多音字是怎么处理的？

### ISSUE THREAD

**Issue by laubonghaudoi** [biopolyhedron/middle-chinese-text-label#2]
在标注唐诗三百首的时候，不可避免会遇到多音字，这时候是通过格律来去掉不符合韵律的字吗？如果遇到一些多音字，即使根据格律去除不合平仄的音后还是存在多个发音，则怎么处理？例如《终南山》的首联：

> 太乙近天都 連山接海隅

可以看到文件中被标注为：

> Thad qit gionx Then-to, lien sren tauh haix ngyo.

其中的“近”字是多音字，既可以是上声也可以是去声，这时是靠什么确定标为上声的呢？

另外，大写字母和横杠又有什么意义呢？例如上句中的Thad 和Then-to。

**Comment by biopolyhedron** [comment]
要査義訓的，看廣韻或康熙字典以及古籍的注。加不加 - 我沒有定則，在連綿詞或人名地名中有時會加。
laubonghaudoi <notifications@github.com> 于 2019年1月13日 周日 15:13写道：

**Comment by laubonghaudoi** [comment]
感谢解答，也就是说三百首诗的标音全都是手工标注并查阅古籍验证，没有用到程序自动标音的吗？

**Comment by biopolyhedron** [comment]
是，全部爲手工標音，當然不敢說標得都對。

laubonghaudoi <notifications@github.com> 于 2019年1月13日 周日 15:51写道：

**Comment by laubonghaudoi** [comment]
明白了，感谢作者的辛勤付出
